On Deploying the odoo module got the error message
odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/nettrades_core/views/nettrades_user_views.xml:4
Invalid view type: 'tree'.
You might have used an invalid starting tag in the architecture.
Allowed types are: list, form, graph, pivot, calendar, kanban, search, qweb, hierarchy, activity

The problem: In Odoo 19, the <tree> view tag has been deprecated and replaced with <list>

Therefore ran:

cd /root/nettrades-platform/odoo-modules

# Replace <tree> with <list> in all XML view files
find . -name "*.xml" -exec sed -i 's/^\([[:space:]]*\)<tree\([[:space:]>]\)/\1<list\2/g' {} +

# Also fix view_mode="tree,form" to "list,form" in action definitions
find . -name "*.xml" -exec sed -i 's/view_mode="tree,form"/view_mode="list,form"/g' {} +

find . -name "*.xml" -exec sed -i 's/<\/tree>/<\/list>/g' {} +
grep -n "tree" nettrades_core/views/nettrades_user_views.xml
find . -name "*.xml" -exec sed -i 's/>tree,form</>list,form</g' {} +
find . -name "*.xml" -exec sed -i 's/kanban,tree,form/kanban,list,form/g' {} +
find . -name "*.xml" -exec sed -i 's/view_mode="tree"/view_mode="list"/g' {} +
grep -rn 'view_mode=.*tree' --include="*.xml" .

To replace the <tree> tag with <list>