Odoo module comment error	Removed/commented out <field name="comment">
In Odoo 19, the ir.rule model does not have a comment field. The nettrades_security.xml included <field name="comment">...</field>
inside record definitions for ir.rule, which causes a

ValueError: Invalid field 'comment' in 'ir.rule'